vim.api.nvim_set_hl(0, "NeoNotebookOutput", { fg = "#a020f0" })
vim.api.nvim_set_hl(0, "NeoNotebookSpinner", { fg = "yellow" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBlack", { fg = "#000000" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiRed", { fg = "#cd3131" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiGreen", { fg = "#0dbc79" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiYellow", { fg = "#e5e510" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBlue", { fg = "#2472c8" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiMagenta", { fg = "#bc3fbc" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiCyan", { fg = "#11a8cd" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiWhite", { fg = "#e5e5e5" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightBlack", { fg = "#666666" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightRed", { fg = "#f14c4c" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightGreen", { fg = "#23d18b" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightYellow", { fg = "#f5f543" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightBlue", { fg = "#3b8eea" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightMagenta", { fg = "#d670d6" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightCyan", { fg = "#29b8db" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightWhite", { fg = "#e5e5e5" })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBlackBold", { fg = "#000000", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiRedBold", { fg = "#cd3131", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiGreenBold", { fg = "#0dbc79", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiYellowBold", { fg = "#e5e510", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBlueBold", { fg = "#2472c8", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiMagentaBold", { fg = "#bc3fbc", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiCyanBold", { fg = "#11a8cd", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiWhiteBold", { fg = "#e5e5e5", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightBlackBold", { fg = "#666666", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightRedBold", { fg = "#f14c4c", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightGreenBold", { fg = "#23d18b", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightYellowBold", { fg = "#f5f543", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightBlueBold", { fg = "#3b8eea", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightMagentaBold", { fg = "#d670d6", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightCyanBold", { fg = "#29b8db", bold = true })
vim.api.nvim_set_hl(0, "NeoNotebookAnsiBrightWhiteBold", { fg = "#ffffff", bold = true })
